services:
  app:
    command: npm run dev
    environment:
      NODE_ENV: development
    ports:
      - "${APP_PORT_HOST:-43000}:3000"
    volumes:
      - .:/app
      - /app/node_modules

  db:
    ports:
      - "${POSTGRES_PORT_HOST:-45432}:5432"

